import type { Locale } from '@/i18n/locale';
import type { PeakProModule } from '@/lib/peakpro/constants';

type CopyTree = Record<string, string>;

const en: CopyTree = {
  brand: 'PeakPro+',
  tagline: 'Institutional market intelligence, refined for the private desk.',
  navOverview: 'Command Desk',
  navPortfolio: 'Book',
  navTape: 'Session Tape',
  navTaiwan: 'Taiwan Equities',
  navUs: 'U.S. Equities',
  navCrypto: 'Crypto Trends',
  navGold: 'Gold Trends',
  navGeopolitics: 'Market News',
  navFilings: 'Public Filings',
  navSentiment: 'Sentiment Desk',
  navTrending: 'Market Movers',
  navBrief: 'AI Weekly Market Summary',
  navAdvisor: 'Desk Advisor',
  navSubscribe: 'Subscribe',
  navLogin: 'Client Access',
  navApp: 'Enter Desk',
  navSignOut: 'Sign Out',
  langEn: 'English',
  langZh: '繁體中文',
  langAria: 'Language switcher',
  clocksTitle: 'World Top 10 Economies Live Clock',
  clocksSub: 'Local session times across the largest economic blocs — 12-hour with AM/PM.',
  heroCta: 'Open the Terminal',
  heroSecondary: 'View Premium Mandate',
  introKicker: 'Anonymous tape · hyper-growth complex',
  lastPrint: 'Updated',
  synchronizing: '',
  freeBadge: 'Free desk',
  premiumBadge: 'Premium mandate',
  lockedTitle: 'Premium mandate required',
  lockedBody:
    'This tape is reserved for PeakPro+ Premium. Free accounts may review monthly trends on TSMC, NVIDIA, Apple, Microsoft, and Tesla only.',
  lockedCta: 'Unlock the full desk',
  monthlyOnly: 'Monthly trends — complimentary hot list',
  dailyTrends: 'Daily · market-wide movers',
  monthlyTrends: 'Monthly Trends',
  annualOutlook: 'Annual Macro Outlook',
  last: 'Last',
  change: 'Change',
  range: 'Range',
  thesis: 'Desk thesis',
  subscribeTitle: 'PeakPro+ Premium Mandate',
  subscribeSub: 'Recurring institutional access. Automatic collection every 30 days via Creem.',
  subscribePrice: '$20',
  subscribePeriod: '/ 30 days',
  subscribeCta: 'Authorize recurring mandate',
  subscribeLogin: 'Sign in to subscribe',
  subscribeFeaturesTitle: 'Unlocked on Premium',
  revokedNotice:
    'The most recent collection failed. Premium access has been revoked immediately. Re-authorize the mandate to restore the full desk.',
  paymentSuccess: 'Mandate confirmed. Premium access is live through the current 30-day cycle.',
  loginTitle: 'Client Access',
  loginSub: 'Sign in to open the PeakPro+ desk.',
  signIn: 'Sign In',
  signUp: 'Open an account',
  email: 'Email',
  password: 'Password',
  backHome: 'Back to PeakPro+',
  overviewLead: '',
  emptyCache: 'Nothing on the desk yet. Please try again shortly.',
  fearTitle: 'Cross-asset sentiment',
  fearLead: '',
  fearTaiwan: 'Taiwan market · bid / offer',
  fearUs: 'U.S. market · bid / offer',
  fearCrypto: 'Crypto · Fear & Greed',
  fearTaiwanHint: '',
  fearUsHint: '',
  fearCryptoHint: '',
  fearSample: 'names',
  fearAvg: 'Avg change',
  trendingTitle: 'Market-wide movers',
  trendingLead: '',
  trendingTaiwan: 'Taiwan market',
  trendingUs: 'U.S. market',
  briefTitle: 'AI Weekly Market Summary',
  newsTitle: 'Market-moving international news',
  newsLead: '',
  filingsTitle: 'Public filings',
  filingsLead: '',
  filingsPoliticians: 'Politicians',
  filingsInvestors: 'Superinvestors',
  filingsBuy: 'Buy',
  filingsSell: 'Sell',
  filingsOther: 'Other',
  filingsDisclosed: 'Disclosed',
  filingsTraded: 'Traded',
  filingsEmpty: 'No filings in this scrape yet.',
  filingsAsOf: 'Report date',
  filingsHoldings: 'Largest reported holdings',
  filingsLink: 'Open source filing',
  filingsHouse: 'House',
  filingsSenate: 'Senate',
  filingsExec: 'Executive',
  catWar: 'War',
  catGeopolitics: 'Geopolitics',
  catMarkets: 'Markets',
  goldTitle: 'Spot Gold',
  cryptoTitle: 'Major cryptocurrency complex',
  taiwanTitle: 'Taiwan market',
  usTitle: 'U.S. market',
  searchPlaceholderTw: 'Search a TWSE code — 2330 or 2330.TW',
  searchPlaceholderUs: 'Search a U.S. ticker — AAPL, NVDA',
  searchCta: 'Look up',
  searchHint: 'Look up any listed ticker.',
  searchWrongMarketTw: 'That looks like a U.S. ticker. Open U.S. Equities to look it up.',
  searchWrongMarketUs: 'That looks like a Taiwan code. Open Taiwan Equities to look it up.',
  searchInvalid: 'Enter a valid ticker.',
  searchNotFound: 'No daily tape found for that symbol.',
  searchPremiumOnly: 'Custom tickers are a Premium desk feature.',
  searchOk: 'Added to the desk.',
  backToDesk: 'Back to desk',
  tapeReadout: 'Tape readout',
  missingSymbol: 'This ticker is not on the desk yet. Look it up first.',
  missingNews: 'This briefing is no longer available.',
  readOriginal: 'Read original',
  monthlyOnlyChart: 'Free desk shows monthly trends only.',
  tvTitle: 'Live tape',
  tvLead: 'TradingView for this name only. Desk marks stay on the warehouse print.',
  tvLocked: 'Live tape is a Premium desk feature.',
  tvOpen: 'Open live chart on TradingView',
  tvOpenHint: 'Taiwan listed names cannot be embedded here. The live chart opens on TradingView.',
  mktCap: 'Mkt cap',
  peLabel: 'P/E',
  weekRange: 'Range',
  open: 'Open',
  highLabel: 'High',
  lowLabel: 'Low',
  close: 'Close',
  volume: 'Volume',
  advisorTitle: 'Desk Advisor',
  advisorLead: 'Ask for a desk call — add, trim, or wait — on Taiwan or U.S. names, crypto, gold, or macro.',
  advisorEmpty: '',
  advisorPlaceholder: 'Ask in any language — e.g. is NVDA still a buy, or 2330 適合買進嗎',
  advisorSend: 'Send',
  advisorClear: 'Clear thread',
  advisorFoot: '',
  advisorQuota: '{used} / {limit} messages today',
  advisorQuotaLoading: 'Checking desk quota…',
  advisorQuotaPending: '',
  advisorOffline: 'Desk Advisor is temporarily unavailable.',
  advisorLimit: 'Daily advisor limit reached. Try again after midnight Taipei time.',
  advisorTooLong: 'That question is too long.',
  advisorFailed: 'The advisor could not complete that turn.',
  advisorNeedPremium: 'Desk Advisor is a Premium mandate feature.',
  advisorNeedLogin: 'Sign in to use Desk Advisor.',
  bookTitle: 'Personal book',
  bookLead: 'Lots you enter. Switch to 中文 to read U.S. marks in TWD.',
  bookAdd: 'Add a lot',
  book_taiwan: 'Taiwan',
  book_us: 'U.S.',
  book_crypto: 'Crypto',
  book_gold: 'Gold',
  bookSymbol: 'Ticker / code',
  bookGoldHint: 'XAU or GOLD',
  bookCryptoHint: 'BTC or ETH',
  bookQty: 'Quantity',
  bookUnitCost: 'Cost / unit',
  bookCost: 'Cost basis',
  bookMarket: 'Mark',
  bookPnl: 'P&L',
  bookDate: 'Bought',
  bookSave: 'Add',
  bookDelete: 'Remove lot',
  bookEmpty: 'No lots yet. Add a ticker, quantity, and your cost.',
  bookLoading: 'Loading the book…',
  bookFailed: 'Could not update the book.',
  bookSetup: 'Run migration 003_peakpro_portfolio.sql on the PeakPro Supabase project.',
  bookLimit: 'The book holds 40 lots. Remove one first.',
  bookNotFound: 'No quote for that symbol.',
  bookInvalid: 'Taiwan codes are four digits, e.g. 2330. Gold: XAU or GOLD.',
  bookWrongMarket: 'That ticker does not match the selected book.',
  bookFoot: '',
  tapeTitle: 'Session Tape',
  tapeLead: 'Volume-price turns from the whole Taiwan and U.S. tape. Official TWSE/TPEX institutions after the close.',
  tapeBook: 'Lots in your book',
  tapeDesk: 'Market-wide tape',
  tapeTaiwan: 'Taiwan vs 0050',
  tapeUs: 'U.S. vs QQQ',
  tapeTurn: 'Turn',
  tapeRs: 'vs index',
  tapeVol: 'Volume vs 20d',
  tapeRange: 'Day range',
  tapeInst: 'Official institutions',
  tapeInstDate: 'TWSE / TPEX session',
  tapeForeign: 'Foreign',
  tapeTrust: 'Trusts',
  tapeDealer: 'Dealers',
  tapeTotal: 'Three institutions',
  tapeStreak: 'Streak',
  tapeNoInst: 'U.S. names have no TWSE institution file.',
  tapePendingInst: 'After-close institutions not in yet.',
  tapeEmpty: 'Nothing on the tape yet. Please try again shortly.',
  tapeSetup: 'Run migration 004_peakpro_tape.sql on the PeakPro Supabase project.',
  tapeLoading: 'Reading the session tape…',
  tapeFoot: '',
  tape_thrust: 'Thrust',
  tape_fade: 'Fade',
  tape_press: 'Press',
  tape_idle: 'Idle',
  tape_first: 'First print',
  tape_flat: 'Flat',
  tape_lead: 'Lead',
  tape_lag: 'Lag',
  tape_inline: 'In line',
  tapeLeadCount: 'leading',
  tapeLagCount: 'lagging',
  tapeBookPulse: 'Book turns',
  tapePrints: 'snapshots',
  footerProduct: 'PeakPro+ Market Intelligence',
};

const zh: CopyTree = {
  brand: 'PeakPro+',
  tagline: '機構級市場情報，為私人投資桌重新淬鍊。',
  navOverview: '指揮台',
  navPortfolio: '組合',
  navTape: '動能轉折',
  navTaiwan: '台股',
  navUs: '美股',
  navCrypto: '加密趨勢',
  navGold: '黃金趨勢',
  navGeopolitics: '國際財經情報',
  navFilings: '公開申報',
  navSentiment: '市場情緒',
  navTrending: '全市場熱門',
  navBrief: 'AI 每週市場總結',
  navAdvisor: '桌面顧問',
  navSubscribe: '訂閱',
  navLogin: '客戶登入',
  navApp: '進入終端',
  navSignOut: '登出',
  langEn: 'English',
  langZh: '繁體中文',
  langAria: '語言切換',
  clocksTitle: '全球十大經濟體即時時鐘',
  clocksSub: '十大經濟體當地時間，12 小時制並標示上午／下午。',
  heroCta: '開啟終端',
  heroSecondary: '查看 Premium 授權',
  introKicker: '匿名走勢 · 超成長科技複合體',
  lastPrint: '更新',
  synchronizing: '',
  freeBadge: '免費桌',
  premiumBadge: 'Premium 授權',
  lockedTitle: '需 Premium 授權',
  lockedBody:
    '此情報僅供 PeakPro+ Premium 使用。免費帳戶僅可檢視台積電、NVIDIA、蘋果、微軟與特斯拉的月線趨勢。',
  lockedCta: '解鎖完整終端',
  monthlyOnly: '月線趨勢 — 免費熱門清單',
  dailyTrends: '日線 · 全市場熱門',
  monthlyTrends: '月線趨勢',
  annualOutlook: '年度總體展望',
  last: '最新價',
  change: '漲跌',
  range: '區間',
  thesis: '桌面論點',
  subscribeTitle: 'PeakPro+ Premium 授權',
  subscribeSub: '機構級循環權限。透過 Creem 每 30 日自動請款。',
  subscribePrice: '$20',
  subscribePeriod: '/ 30 日',
  subscribeCta: '授權循環請款',
  subscribeLogin: '登入後訂閱',
  subscribeFeaturesTitle: 'Premium 解鎖模組',
  revokedNotice: '最近一次請款失敗，Premium 權限已立即撤銷。請重新授權以恢復完整終端。',
  paymentSuccess: '授權已確認。Premium 權限於本 30 日週期內生效。',
  loginTitle: '客戶登入',
  loginSub: '登入後進入 PeakPro+ 終端。',
  signIn: '登入',
  signUp: '開立帳戶',
  email: '電子郵件',
  password: '密碼',
  backHome: '返回 PeakPro+',
  overviewLead: '',
  emptyCache: '資料準備中，請稍候再試。',
  fearTitle: '跨資產情緒',
  fearLead: '',
  fearTaiwan: '台股全市場 · 利多／利空',
  fearUs: '美股全市場 · 利多／利空',
  fearCrypto: '加密 · 恐懼／貪婪',
  fearTaiwanHint: '',
  fearUsHint: '',
  fearCryptoHint: '',
  fearSample: '檔',
  fearAvg: '平均漲跌',
  trendingTitle: '全市場熱門',
  trendingLead: '',
  trendingTaiwan: '台股全市場',
  trendingUs: '美股全市場',
  briefTitle: 'AI 每週市場總結',
  newsTitle: '會動股價的國際新聞',
  newsLead: '',
  filingsTitle: '公開申報',
  filingsLead: '',
  filingsPoliticians: '政治人物',
  filingsInvestors: '知名法人',
  filingsBuy: '買進',
  filingsSell: '賣出',
  filingsOther: '其他',
  filingsDisclosed: '申報日',
  filingsTraded: '交易日',
  filingsEmpty: '這一輪還沒抓到申報。',
  filingsAsOf: '報告日',
  filingsHoldings: '申報最大持股',
  filingsLink: '打開原始申報',
  filingsHouse: '眾議院',
  filingsSenate: '參議院',
  filingsExec: '行政',
  catWar: '戰事',
  catGeopolitics: '地緣政治',
  catMarkets: '市場',
  goldTitle: '現貨黃金',
  cryptoTitle: '主要加密貨幣複合體',
  taiwanTitle: '台股全市場',
  usTitle: '美股全市場',
  searchPlaceholderTw: '查台股代碼 — 2330 或 2330.TW',
  searchPlaceholderUs: '查美股代碼 — AAPL、NVDA',
  searchCta: '查詢',
  searchHint: '可查全市場任何一檔。',
  searchWrongMarketTw: '這比較像美股代碼，請到美股頁查詢。',
  searchWrongMarketUs: '這比較像台股代碼，請到台股頁查詢。',
  searchInvalid: '請輸入有效代碼。',
  searchNotFound: '找不到這檔的日線資料。',
  searchPremiumOnly: '自選代碼需 Premium。',
  searchOk: '已加入列表。',
  backToDesk: '返回列表',
  tapeReadout: '走勢讀數',
  missingSymbol: '這檔還沒在列表上，請先查詢。',
  missingNews: '這則情報已不在。',
  readOriginal: '閱讀原文',
  monthlyOnlyChart: '免費桌僅顯示月線。',
  tvTitle: '即時走勢',
  tvLead: '只為這一檔載入 TradingView。桌上損益仍用快取價。',
  tvLocked: '即時走勢需 Premium。',
  tvOpen: '在 TradingView 開啟即時圖',
  tvOpenHint: '台灣上市股票不能嵌在本頁，會另開 TradingView 看即時圖。上櫃與美股可直接顯示。',
  mktCap: '市值',
  peLabel: '本益比',
  weekRange: '區間',
  open: '開',
  highLabel: '高',
  lowLabel: '低',
  close: '收',
  volume: '量',
  advisorTitle: '桌面顧問',
  advisorLead: '可直接問適不適合買進、減碼或觀望。台股、美股、加密、黃金、總體都可以。',
  advisorEmpty: '',
  advisorPlaceholder: '用任何語言提問 — 例如 NVDA 還能買嗎、或 2330 適合買進嗎',
  advisorSend: '送出',
  advisorClear: '清除對話',
  advisorFoot: '',
  advisorQuota: '今日已用 {used} / {limit} 則',
  advisorQuotaLoading: '正在讀取配額…',
  advisorQuotaPending: '',
  advisorOffline: '桌面顧問暫時無法使用。',
  advisorLimit: '今日顧問則數已用完。台北時間午夜後再試。',
  advisorTooLong: '這則問題太長。',
  advisorFailed: '這一則沒有完成。',
  advisorNeedPremium: '桌面顧問僅供 Premium 使用。',
  advisorNeedLogin: '請先登入再使用桌面顧問。',
  bookTitle: '自選組合',
  bookLead: '你自己輸入的部位。中文介面美股以台幣計價。',
  bookAdd: '新增部位',
  book_taiwan: '台股',
  book_us: '美股',
  book_crypto: '加密',
  book_gold: '黃金',
  bookSymbol: '代碼',
  bookGoldHint: 'XAU 或 GOLD',
  bookCryptoHint: 'BTC 或 ETH',
  bookQty: '數量',
  bookUnitCost: '單位成本',
  bookCost: '成本',
  bookMarket: '市值',
  bookPnl: '損益',
  bookDate: '買入日',
  bookSave: '加入',
  bookDelete: '刪除部位',
  bookEmpty: '還沒有部位。輸入代碼、數量與你的成本即可。',
  bookLoading: '正在讀取組合…',
  bookFailed: '組合更新失敗。',
  bookSetup: '請在 PeakPro 的 Supabase 執行 003_peakpro_portfolio.sql。',
  bookLimit: '組合最多 40 筆，請先刪一筆。',
  bookNotFound: '找不到這檔報價。',
  bookInvalid: '台股請填四碼，例如 2330 或 2330.TW。黃金填 XAU 或 GOLD。',
  bookWrongMarket: '代碼與所選市場不符。',
  bookFoot: '',
  tapeTitle: '動能轉折',
  tapeLead: '從全台股、全美股抓量價轉折；台股三大法人是盤後官方數字。',
  tapeBook: '你的持倉',
  tapeDesk: '全市場熱門',
  tapeTaiwan: '台股相對 0050',
  tapeUs: '美股相對 QQQ',
  tapeTurn: '轉折',
  tapeRs: '相對指數',
  tapeVol: '量能／20日',
  tapeRange: '當日位置',
  tapeInst: '盤後法人（官方）',
  tapeInstDate: '證交所／櫃買日',
  tapeForeign: '外資',
  tapeTrust: '投信',
  tapeDealer: '自營',
  tapeTotal: '三大法人',
  tapeStreak: '連續',
  tapeNoInst: '美股沒有證交所三大法人檔。',
  tapePendingInst: '盤後法人尚未公布。',
  tapeEmpty: '資料準備中，請稍候再試。',
  tapeSetup: '請在 PeakPro 的 Supabase 執行 004_peakpro_tape.sql。',
  tapeLoading: '正在讀取動能表…',
  tapeFoot: '',
  tape_thrust: '轉強',
  tape_fade: '上攻縮量',
  tape_press: '轉弱',
  tape_idle: '回落縮量',
  tape_first: '首筆',
  tape_flat: '持平',
  tape_lead: '領先',
  tape_lag: '落後',
  tape_inline: '同步',
  tapeLeadCount: '檔領先',
  tapeLagCount: '檔落後',
  tapeBookPulse: '持倉轉折',
  tapePrints: '筆快照',
  footerProduct: 'PeakPro+ 市場情報',
};

const dictionaries: Record<Locale, CopyTree> = { en, zh };

export function peakproCopy(locale: Locale): CopyTree {
  return dictionaries[locale];
}

export function tPeakpro(locale: Locale, key: string): string {
  return dictionaries[locale][key] ?? dictionaries.en[key] ?? key;
}

function hasCjk(value: string | null | undefined): boolean {
  return Boolean(value && /[\u3400-\u9fff]/.test(value));
}

export function localizedNewsText(locale: Locale, en: string, zh: string | null | undefined) {
  if (locale === 'zh' && zh && (hasCjk(zh) || zh !== en)) return zh;
  return en;
}

export function newsCategoryLabel(locale: Locale, category: string) {
  if (category === 'war') return tPeakpro(locale, 'catWar');
  if (category === 'markets') return tPeakpro(locale, 'catMarkets');
  return tPeakpro(locale, 'catGeopolitics');
}

const SOURCE_LABELS: Record<string, { en: string; zh: string }> = {
  'BBC World': { en: 'BBC World', zh: 'BBC 國際' },
  'BBC Business': { en: 'BBC Business', zh: 'BBC 財經' },
  'NYT World': { en: 'NYT World', zh: '紐約時報國際' },
  'NYT Business': { en: 'NYT Business', zh: '紐約時報財經' },
  'Guardian World': { en: 'Guardian World', zh: '衛報國際' },
  'Guardian Business': { en: 'Guardian Business', zh: '衛報財經' },
  'Al Jazeera': { en: 'Al Jazeera', zh: '半島電視' },
  'CNBC World': { en: 'CNBC World', zh: 'CNBC 國際' },
  'CNBC Economy': { en: 'CNBC Economy', zh: 'CNBC 經濟' },
  MarketWatch: { en: 'MarketWatch', zh: 'MarketWatch' },
  'Federal Reserve': { en: 'Federal Reserve', zh: '聯準會' },
  OilPrice: { en: 'OilPrice', zh: '油價' },
};

export function newsSourceLabel(locale: Locale, source: string) {
  const row = SOURCE_LABELS[source];
  if (row) return locale === 'zh' ? row.zh : row.en;
  return source;
}

export const MODULE_HREF: Record<PeakProModule, string> = {
  overview: '/app',
  portfolio: '/app/portfolio',
  tape: '/app/tape',
  taiwan: '/app/taiwan',
  us: '/app/us',
  crypto: '/app/crypto',
  gold: '/app/gold',
  geopolitics: '/app/geopolitics',
  filings: '/app/filings',
  sentiment: '/app/sentiment',
  trending: '/app/trending',
  brief: '/app/brief',
  advisor: '/app/advisor',
};

export function moduleLabel(locale: Locale, moduleId: PeakProModule): string {
  const keys: Record<PeakProModule, string> = {
    overview: 'navOverview',
    portfolio: 'navPortfolio',
    tape: 'navTape',
    taiwan: 'navTaiwan',
    us: 'navUs',
    crypto: 'navCrypto',
    gold: 'navGold',
    geopolitics: 'navGeopolitics',
    filings: 'navFilings',
    sentiment: 'navSentiment',
    trending: 'navTrending',
    brief: 'navBrief',
    advisor: 'navAdvisor',
  };
  return tPeakpro(locale, keys[moduleId]);
}
