import type { Locale } from '@/i18n/locale';
import type { PeakProModule } from '@/lib/peakpro/constants';

type CopyTree = Record<string, string>;

const en: CopyTree = {
  brand: 'PeakPro+',
  tagline: 'Institutional market intelligence, refined for the private desk.',
  navOverview: 'Command Desk',
  navTaiwan: 'Taiwan Equities',
  navUs: 'U.S. Equities',
  navCrypto: 'Crypto Trends',
  navGold: 'Gold Trends',
  navGeopolitics: 'Geopolitical Risk Feed',
  navSentiment: 'Sentiment Desk',
  navTrending: 'Weekly Trending Assets',
  navBrief: 'AI Weekly Market Summary',
  navAdvisor: 'Desk Advisor',
  navSubscribe: 'Subscribe',
  navLogin: 'Client Access',
  navApp: 'Enter Desk',
  navSignOut: 'Sign Out',
  langEn: 'English',
  langZh: '繁體中文',
  langAria: 'Language switcher',
  clocksTitle: 'World Top 10 Economies Live Clock',
  clocksSub: 'Local session times across the largest economic blocs — 12-hour with AM/PM.',
  heroCta: 'Open the Terminal',
  heroSecondary: 'View Premium Mandate',
  introKicker: 'Anonymous tape · hyper-growth complex',
  lastPrint: 'Last cache print',
  synchronizing: 'The market desk is synchronizing the local cache. No live vendor calls are made from this session.',
  freeBadge: 'Free desk',
  premiumBadge: 'Premium mandate',
  lockedTitle: 'Premium mandate required',
  lockedBody:
    'This tape is reserved for PeakPro+ Premium. Free accounts may review monthly trends on TSMC, NVIDIA, Apple, Microsoft, and Tesla only.',
  lockedCta: 'Unlock the full desk',
  monthlyOnly: 'Monthly trends — complimentary hot list',
  dailyTrends: 'Daily Trends',
  monthlyTrends: 'Monthly Trends',
  annualOutlook: 'Annual Macro Outlook',
  last: 'Last',
  change: 'Change',
  range: 'Range',
  thesis: 'Desk thesis',
  subscribeTitle: 'PeakPro+ Premium Mandate',
  subscribeSub: 'Recurring institutional access. Automatic collection every 30 days via Creem.',
  subscribePrice: '$20',
  subscribePeriod: '/ 30 days',
  subscribeCta: 'Authorize recurring mandate',
  subscribeLogin: 'Sign in to subscribe',
  subscribeFeaturesTitle: 'Unlocked on Premium',
  revokedNotice:
    'The most recent collection failed. Premium access has been revoked immediately. Re-authorize the mandate to restore the full desk.',
  paymentSuccess: 'Mandate confirmed. Premium access is live through the current 30-day cycle.',
  loginTitle: 'Client Access',
  loginSub: 'Authenticate to read the PeakPro+ cache. External market vendors are never called from the browser.',
  signIn: 'Sign In',
  signUp: 'Open an account',
  email: 'Email',
  password: 'Password',
  backHome: 'Back to PeakPro+',
  overviewLead: 'Cached prints only. The scraper desk refreshes the warehouse every three hours.',
  emptyCache: 'No cached prints yet. The background scraper has not completed its first cycle.',
  fearTitle: 'Cross-asset sentiment',
  fearLead:
    'Three labeled gauges on one page. Taiwan and U.S. are bid/offer from the hot-list daily cache. Crypto is the Bitcoin Fear & Greed index — not a cash-equity print.',
  fearTaiwan: 'Taiwan equities · bid / offer',
  fearUs: 'U.S. equities · bid / offer',
  fearCrypto: 'Crypto · Fear & Greed',
  fearTaiwanHint: 'Desk names only: 2330, Hon Hai, MediaTek daily cache.',
  fearUsHint: 'Desk names only: TSM ADR, NVDA, AAPL, MSFT, TSLA and the U.S. hot list.',
  fearCryptoHint: 'Bitcoin Fear & Greed (alternative.me cache). Not Taiwan or U.S. stocks.',
  fearSample: 'names in print',
  fearAvg: 'Avg change',
  trendingTitle: 'Weekly Trending Assets',
  briefTitle: 'AI Weekly Market Summary',
  newsTitle: 'Geopolitical & War News',
  catWar: 'War',
  catGeopolitics: 'Geopolitics',
  sourceBbc: 'BBC World',
  sourceNyt: 'NYT World',
  goldTitle: 'Spot Gold',
  cryptoTitle: 'Major cryptocurrency complex',
  taiwanTitle: 'Taiwan cash equities',
  usTitle: 'U.S. cash equities',
  searchPlaceholderTw: 'Search a TWSE code — 2330 or 2330.TW',
  searchPlaceholderUs: 'Search a U.S. ticker — AAPL, NVDA',
  searchCta: 'Look up',
  searchHint: 'Look up a ticker to add it to the local cache.',
  searchWrongMarketTw: 'That looks like a U.S. ticker. Open U.S. Equities to look it up.',
  searchWrongMarketUs: 'That looks like a Taiwan code. Open Taiwan Equities to look it up.',
  searchInvalid: 'Enter a valid ticker.',
  searchNotFound: 'No daily tape found for that symbol.',
  searchPremiumOnly: 'Custom tickers are a Premium desk feature.',
  searchOk: 'Added to the desk cache.',
  backToDesk: 'Back to desk',
  tapeReadout: 'Tape readout',
  missingSymbol: 'This ticker is not in the warehouse yet. Look it up from the desk first.',
  missingNews: 'This briefing is no longer in the cache.',
  readOriginal: 'Read original',
  monthlyOnlyChart: 'Free desk shows the monthly cache only.',
  mktCap: 'Mkt cap',
  peLabel: 'P/E',
  weekRange: 'Cached range',
  open: 'Open',
  highLabel: 'High',
  lowLabel: 'Low',
  close: 'Close',
  volume: 'Volume',
  advisorTitle: 'Desk Advisor',
  advisorLead:
    'A finance-only desk model. It answers in the language you type, using PeakPro+ cache prints for levels — not a live tape, and not a buy or sell order.',
  advisorEmpty: 'Ask about Taiwan or U.S. equities, crypto, gold, or macro risk. Unrelated requests will be declined.',
  advisorPlaceholder: 'Ask in any language — e.g. why is TSM moving, or 比特幣恐懼指數怎麼讀',
  advisorSend: 'Send',
  advisorClear: 'Clear thread',
  advisorFoot: 'Session-only thread. 30 messages per Taipei calendar day. Educational, not advice.',
  advisorQuota: '{used} / {limit} messages today',
  advisorQuotaLoading: 'Checking desk quota…',
  advisorQuotaPending: 'Quota table not applied yet — chat still runs.',
  advisorOffline: 'Desk Advisor is offline until OPENROUTER_API_KEY is set.',
  advisorLimit: 'Daily advisor limit reached. Try again after midnight Taipei time.',
  advisorTooLong: 'That question is too long.',
  advisorFailed: 'The advisor could not complete that turn.',
  advisorNeedPremium: 'Desk Advisor is a Premium mandate feature.',
  advisorNeedLogin: 'Sign in to use Desk Advisor.',
  footerProduct: 'PeakPro+ Market Intelligence',
};

const zh: CopyTree = {
  brand: 'PeakPro+',
  tagline: '機構級市場情報，為私人投資桌重新淬鍊。',
  navOverview: '指揮台',
  navTaiwan: '台股',
  navUs: '美股',
  navCrypto: '加密趨勢',
  navGold: '黃金趨勢',
  navGeopolitics: '地緣政治風險情報',
  navSentiment: '市場情緒',
  navTrending: '本週熱門資產',
  navBrief: 'AI 每週市場總結',
  navAdvisor: '桌面顧問',
  navSubscribe: '訂閱',
  navLogin: '客戶登入',
  navApp: '進入終端',
  navSignOut: '登出',
  langEn: 'English',
  langZh: '繁體中文',
  langAria: '語言切換',
  clocksTitle: '全球十大經濟體即時時鐘',
  clocksSub: '十大經濟體當地時間，12 小時制並標示上午／下午。',
  heroCta: '開啟終端',
  heroSecondary: '查看 Premium 授權',
  introKicker: '匿名走勢 · 超成長科技複合體',
  lastPrint: '快取最後更新',
  synchronizing: '市場桌正在同步本地快取。此工作階段不會向外部行情商發起即時請求。',
  freeBadge: '免費桌',
  premiumBadge: 'Premium 授權',
  lockedTitle: '需 Premium 授權',
  lockedBody:
    '此情報僅供 PeakPro+ Premium 使用。免費帳戶僅可檢視台積電、NVIDIA、蘋果、微軟與特斯拉的月線趨勢。',
  lockedCta: '解鎖完整終端',
  monthlyOnly: '月線趨勢 — 免費熱門清單',
  dailyTrends: '日線趨勢',
  monthlyTrends: '月線趨勢',
  annualOutlook: '年度總體展望',
  last: '最新價',
  change: '漲跌',
  range: '區間',
  thesis: '桌面論點',
  subscribeTitle: 'PeakPro+ Premium 授權',
  subscribeSub: '機構級循環權限。透過 Creem 每 30 日自動請款。',
  subscribePrice: '$20',
  subscribePeriod: '/ 30 日',
  subscribeCta: '授權循環請款',
  subscribeLogin: '登入後訂閱',
  subscribeFeaturesTitle: 'Premium 解鎖模組',
  revokedNotice: '最近一次請款失敗，Premium 權限已立即撤銷。請重新授權以恢復完整終端。',
  paymentSuccess: '授權已確認。Premium 權限於本 30 日週期內生效。',
  loginTitle: '客戶登入',
  loginSub: '驗證後僅讀取 PeakPro+ 本地快取。瀏覽器不會呼叫外部行情商。',
  signIn: '登入',
  signUp: '開立帳戶',
  email: '電子郵件',
  password: '密碼',
  backHome: '返回 PeakPro+',
  overviewLead: '僅顯示快取報價。背景爬蟲每三小時更新倉儲。',
  emptyCache: '尚無快取報價。背景爬蟲尚未完成首次週期。',
  fearTitle: '跨資產情緒',
  fearLead:
    '同一頁三個儀表，各自標名。台股、美股是熱門清單日線的利多／利空；加密是比特幣恐懼與貪婪指數，不是台股或美股。',
  fearTaiwan: '台股 · 利多／利空',
  fearUs: '美股 · 利多／利空',
  fearCrypto: '加密 · 恐懼／貪婪',
  fearTaiwanHint: '僅桌上三檔：2330、鴻海、聯發科的日線快取。',
  fearUsHint: '僅桌上美股熱門清單日線（含台積電 ADR）。',
  fearCryptoHint: '比特幣恐懼與貪婪指數（alternative.me 快取），不是台股或美股。',
  fearSample: '檔在快取中',
  fearAvg: '平均漲跌',
  trendingTitle: '本週熱門資產',
  briefTitle: 'AI 每週市場總結',
  newsTitle: '地緣政治與戰事新聞',
  catWar: '戰事',
  catGeopolitics: '地緣政治',
  sourceBbc: 'BBC 國際',
  sourceNyt: '紐約時報國際',
  goldTitle: '現貨黃金',
  cryptoTitle: '主要加密貨幣複合體',
  taiwanTitle: '台股現貨',
  usTitle: '美股現貨',
  searchPlaceholderTw: '查台股代碼 — 2330 或 2330.TW',
  searchPlaceholderUs: '查美股代碼 — AAPL、NVDA',
  searchCta: '查詢',
  searchHint: '查詢代碼後會加入快取。',
  searchWrongMarketTw: '這比較像美股代碼，請到美股頁查詢。',
  searchWrongMarketUs: '這比較像台股代碼，請到台股頁查詢。',
  searchInvalid: '請輸入有效代碼。',
  searchNotFound: '找不到這檔的日線資料。',
  searchPremiumOnly: '自選代碼需 Premium。',
  searchOk: '已加入快取。',
  backToDesk: '返回列表',
  tapeReadout: '走勢讀數',
  missingSymbol: '這檔還沒進快取。請先在列表頁查詢。',
  missingNews: '這則情報已不在快取中。',
  readOriginal: '閱讀原文',
  monthlyOnlyChart: '免費桌僅顯示月線快取。',
  mktCap: '市值',
  peLabel: '本益比',
  weekRange: '快取區間',
  open: '開',
  highLabel: '高',
  lowLabel: '低',
  close: '收',
  volume: '量',
  advisorTitle: '桌面顧問',
  advisorLead:
    '金融專用桌面模型。你用哪種語言問，就用哪種語言答；價位以 PeakPro+ 快取為準，不是即時盤，也不下單。',
  advisorEmpty: '可問台股、美股、加密、黃金或總體風險。明顯跑題會被拒絕。',
  advisorPlaceholder: '用任何語言提問 — 例如為什麼 TSM 在動、或比特幣恐懼指數怎麼讀',
  advisorSend: '送出',
  advisorClear: '清除對話',
  advisorFoot: '對話只留在這個分頁。台北時間每日 30 則。僅供教育，非投資建議。',
  advisorQuota: '今日已用 {used} / {limit} 則',
  advisorQuotaLoading: '正在讀取配額…',
  advisorQuotaPending: '配額欄位尚未建立，聊天仍可使用。',
  advisorOffline: '尚未設定 OPENROUTER_API_KEY，桌面顧問無法連線。',
  advisorLimit: '今日顧問則數已用完。台北時間午夜後再試。',
  advisorTooLong: '這則問題太長。',
  advisorFailed: '這一則沒有完成。',
  advisorNeedPremium: '桌面顧問僅供 Premium 使用。',
  advisorNeedLogin: '請先登入再使用桌面顧問。',
  footerProduct: 'PeakPro+ 市場情報',
};

const dictionaries: Record<Locale, CopyTree> = { en, zh };

export function peakproCopy(locale: Locale): CopyTree {
  return dictionaries[locale];
}

export function tPeakpro(locale: Locale, key: string): string {
  return dictionaries[locale][key] ?? dictionaries.en[key] ?? key;
}

function hasCjk(value: string | null | undefined): boolean {
  return Boolean(value && /[\u3400-\u9fff]/.test(value));
}

export function localizedNewsText(locale: Locale, en: string, zh: string | null | undefined) {
  if (locale === 'zh' && zh && (hasCjk(zh) || zh !== en)) return zh;
  return en;
}

export function newsCategoryLabel(locale: Locale, category: string) {
  return tPeakpro(locale, category === 'war' ? 'catWar' : 'catGeopolitics');
}

export function newsSourceLabel(locale: Locale, source: string) {
  if (source === 'BBC World') return tPeakpro(locale, 'sourceBbc');
  if (source === 'NYT World') return tPeakpro(locale, 'sourceNyt');
  return source;
}

export const MODULE_HREF: Record<PeakProModule, string> = {
  overview: '/app',
  taiwan: '/app/taiwan',
  us: '/app/us',
  crypto: '/app/crypto',
  gold: '/app/gold',
  geopolitics: '/app/geopolitics',
  sentiment: '/app/sentiment',
  trending: '/app/trending',
  brief: '/app/brief',
  advisor: '/app/advisor',
};

export function moduleLabel(locale: Locale, moduleId: PeakProModule): string {
  const keys: Record<PeakProModule, string> = {
    overview: 'navOverview',
    taiwan: 'navTaiwan',
    us: 'navUs',
    crypto: 'navCrypto',
    gold: 'navGold',
    geopolitics: 'navGeopolitics',
    sentiment: 'navSentiment',
    trending: 'navTrending',
    brief: 'navBrief',
    advisor: 'navAdvisor',
  };
  return tPeakpro(locale, keys[moduleId]);
}
